name: Build and Deploy Microservices
run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
on: [push]
jobs:
  listfiles:
    runs-on: ubuntu-latest
    outputs: 
      changedfiles: ${{ steps.listchangedfiles.outputs.changedfiles }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'Micros/'

      - name: List all changed files
        id: listchangedfiles
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          ARRAY=()
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            ARRAY+=($file)
          done
          echo "DEBUG: All changed files: $ARRAY"
          echo "${ARRAY[@]}"
          matrix=$(jq --compact-output --null-input '$ARGS.positional' --args -- "${ARRAY[@]}")
          echo "DEBUG: Json Matrix: $matrix"
          echo "changedfiles=$(echo ${matrix})" >> $GITHUB_OUTPUT
         
  microservices:
    needs: listfiles
    if: ${{ needs.listfiles.outputs.changedfiles != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        changedfiles: ${{ fromJson(needs.listfiles.outputs.changedfiles) }}
      max-parallel: 3
    steps:
      - uses: actions/checkout@v4

      - name: execution
        run: |
          sh ${{ matrix.changedfiles }}
 
    